# fly.toml app configuration file generated on 2023-05-28T19:23:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'cdg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
